// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Dyxv975FbEm1OSWX9WRM9UYi9nsXpME',
    appId: '1:17440083627:web:eb417bb8e0d79dfc6df1ee',
    messagingSenderId: '17440083627',
    projectId: 'submit-7905b',
    authDomain: 'submit-7905b.firebaseapp.com',
    storageBucket: 'submit-7905b.appspot.com',
    measurementId: 'G-NYQN44T6H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYAvcNH64AyuUYnsVR757QmJHLxKT77HQ',
    appId: '1:17440083627:android:33be19c27d5da29a6df1ee',
    messagingSenderId: '17440083627',
    projectId: 'submit-7905b',
    storageBucket: 'submit-7905b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU8xCsqZR8T_0IybI4Xj9P9aCV4vZLopI',
    appId: '1:17440083627:ios:56c0188fab5982036df1ee',
    messagingSenderId: '17440083627',
    projectId: 'submit-7905b',
    storageBucket: 'submit-7905b.appspot.com',
    iosBundleId: 'com.example.assigmentApp',
  );
}
